<nav class="menu">
	<ul>
		<li class="<?php if($page=='home'){echo 'active';}?>"><a href="index.php">Home</a></li>
		<li class="<?php if($page=='jayda'){echo 'active';}?>"><a href="student3.php">Jayda Medina</a></li>
		<li class="<?php if($page=='jonathan'){echo 'active';}?>"><a href="student1.php">Jonathan Roman</a></li>
		<li class="<?php if($page=='victoria'){echo 'active';}?>"><a href="student2.php">Victoria Bongard</a></li>
	</ul>
</nav>