<nav class="menu">
	<ul>
		<li class="<?php echo ($_SERVER['PHP_SELF'] == "/index.php" ? "active" : "");?>"><a href="index.php">Home</a></li>
		<li class="<?php echo ($_SERVER['PHP_SELF'] == "/student3.php" ? "active" : "");?>"><a href="student3.php">Jayda Medina</a></li>
		<li class="<?php echo ($_SERVER['PHP_SELF'] == "/student1.php" ? "active" : "");?>"><a href="student1.php">Jonathan Roman</a></li>
		<li class="<?php echo ($_SERVER['PHP_SELF'] == "/student2.php" ? "active" : "");?>"><a href="student2.php">Victoria Bongard</a></li>
	</ul>
</nav>